services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data_rawg:/var/lib/postgresql/data
      # Fjern eller kommenter ud hvis movie-seed.sql ikke eksisterer
      # - ./seeder/movie-seed.sql:/docker-entrypoint-initdb.d/movie-seed.sql

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules  # Tilføj denne for at undgå node_modules konflikter
    ports:
      - "5001:5000"
    environment:
      # Database configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: movie_db
      DB_USER: postgres
      DB_PASSWORD: password
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/movie_db"
      DB_TYPE: postgres
      
      # TMDB API
      TMDB_API_KEY: 1f6dc7215bb66ffdda1d1db32d0fb343
      
      # App configuration
      SERVER_URL: http://localhost:5000
      NODE_ENV: development
      PORT: 5000
    depends_on:
      - postgres

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data_rawg: